export default {
  '1': [
    ['Am', 'Standing here in an empty room'],
    ['  Em', 'I saw you there and my blood ran cold'],
    ['Am', 'Take me back to that long September'],
    ['Em', "Don't know how I ever let you go"],
    ['Am', "I was young, didn't know 'bout love"],
    ['Em', "You were wild, couldn't get enough"],
    ['Am', 'Gave my heart to another lover'],
    ['Em', "Don't know how I ever let you go"],
  ],
  '2': [
    ['[Pre-Chorus]', 'Am                 E7', 'Find me in another place and time'],
    ['C             G', 'If only, if only you were mine'],
    ['C           E7             Am   G', "But I'm already someone else's baby"],
    ['', '[Chorus]', 'Dm    G', 'Guess I had my last chance'],
    ['C', 'And now this is our last dance'],
    ['Am                                Dm', 'You fell through the cracks in my hands'],
    ['E7', "Hard to say it's over"],
  ],
  '3': [
    ['Am             E7', "But I'm already someone else's (C'mon)"],
    ['', '[Post-Chorus]', 'Dm    G', 'Baby, ahh'],
    ['C     Am', 'Baby, ahh'],
    ['Dm    E7', 'Baby, ahh'],
    ['Am', "I'm already someone else's"],
  ],
  '4': [
    ['[Verse 2]', 'Am', 'All caught up in the way we were'],
    ['Em', 'I feel your hands getting close to mine'],
    ['Am', "Don't say the words that I love to hear"],
    ['Em', 'The beat goes on and I close my eyes'],
    ['Am', "I was young, didn't know 'bout love"],
    ['Em', "You were wild, couldn't get enough"],
    ['Am', "Let's leave things the way they were"],
    ['Em', "You'll stay with me like a lullaby"],
  ],
  '5': [
    ['[Verse 3]', 'Hey'],
    ['Am                         E7', 'Se que te gusto a ti todavia por mucho que digas'],
    [
      'Am                                 E7',
      'Ademas puedo ver en tus ojos que no solo quieres quedar como amigos',
    ],
    ['C                  E7', 'Tienes mi corazón, eres mi obsesión'],
    ['C                  E7', "Soy tuyo pa' siempre"],

    ['', '[Chorus]', 'Dm    G', 'Guess I had my last chance'],
    ['C    Am', 'And now this is our last dance'],
  ],

  '6': [
    ['Dm', 'You fell through the cracks in my hands'],
    ['E7', 'Tell myself be stronger'],
    ['Am             G      C', "My heart's like a rubber band"],
    ['Dm', "And it's such a shame"],
    ['G                          C    Am', "You'll always be the one who got away"],
    ['Dm', 'We both know that deep down you feel the same'],
    ['E7', "Hard to say it's over"],
    ['Am            E7'],
    ["But I'm already someone else's (C'mon)"],

    ['', '[Post-Chorus]', 'Dm    G', 'Baby, ahh (Eso no es amor)'],
  ],

  '7': [
    ['C     Am', 'Baby, ahh (Mereces mejor)'],
    ['Dm    E7', 'Baby, ahh (Quiero tu calor)'],
    ['Am            E7', "I'm already someone else's"],
    ['', '[Bridge]', 'Dm                   G', 'Wish I met you at another place and time'],
    ['C               Am', 'If only, if only you were mine'],
    ['Dm                     E7', 'This love story ends for you and I'],
    ['Am            E7', "'Cause I'm already someone else's"],
  ],
  '8': [
    ['[Post-Chorus]', 'Dm    G', 'Baby, ahh (Y lo digo otra vez)'],
    ['C     Am', 'Baby, ahh (Mereces mucho mejor, mucho mejor)'],
    ['Dm    E7', 'Baby, ahh (Lo que tienes con el no es amor, no)'],
    ['Am            E7', "I'm already someone else's"],
  ],
  '9': [
    ['[Outro]', 'Dm    G', 'Baby, ahh (Cada noche mas te extraño, cada dia sin ti me hace daño)'],
    ['C     Am', 'Baby, ahh (Sabes que mereces mejor, lo que sientes por el ya no es amor)'],
    ['Dm   E7', 'Baby, ahh (Por mucho que digas somos mas que amigos)'],
    [
      'Am             E7          Am',
      "I'm already someone else's   (Y el tiempo se acaba en cuatro, tres, dos, uno)",
    ],
  ],
}
