export default {
  '1': [
    ['Am', 'C’est parti de rien'],
    ['Em', 'A peine un regard échangé'],
    ['F', 'On était deux deux étrangers'],
    ['C', 'Qui se connaissaient bien'],
    ['Am', "C'est parti de loin"],
    ['Em', "Je n'voulais pas me dévoiler"],
    ['F', "Mais ma pudeur tu l'as volée"],
    ['C', 'Le ciel en est témoin'],
  ],
  '2': [
    ['Am                 Am', 'Combien de jours, combien de joies'],
    ['Em', "C'est pas très grave si on n'sait pas"],
    ['F', "Puisqu'une seconde à tes côtés"],
    ['C', 'Vaut bien des années'],
    ['Am               Am', 'Combien de jours, combien de gens'],
    ['Em', "Diront qu'on s'aime obstinémеnt"],
    ['F', "Mais ça m'amuse ma muse"],
    ['C', "On n'est pas prêt dе faner"],
  ],
  '3': [
    ['Am                    Em', 'Si dans ta rétine l’amour'],
    ['F                         C', 'Ne supporte plus la lumière du jour'],
    ['Am                     Em', 'Je rallumerai les étoiles autour'],
    ['F                            C', "J'apprendrai à compter jusqu'à toujours"],
    ['Am', 'Et toi tu pourras compter sur moi'],
  ],
  '4': [
    ['Em', 'Et ça finira jamais'],
    ['F', 'Ça finira jamais'],
    ['C', 'Ça finira jamais'],
    ['Am            Em', 'Ça finira jamais'],
    ['F', 'Ça finira jamais'],
    ['C', 'Ça finira jamais'],
  ],
  '5': [
    ['Am', "Je sais qu'on sera bien"],
    ['Em', 'Comme lèvres douces et peaux salées'],
    ['F', 'Comme quand nos corps se laissent aller'],
    ['C', "L'océan est témoin"],
    ['Am', "J'aime tes manies, notre magie"],
    ['Em', "Ta façon d'être mon amie"],
    ['F', "J'suis pas superstitieux"],
    ['C', "Mais t'es la chance de ma vie"],
  ],
  '6': [
    ['Am', 'Si demain on avait plus rien'],
    ['Em', 'Je te dirais pas à Dieu'],
    ['F', "Mais merci d'avoir laisser"],
    ['C', 'Dans mes tempête Une belle éclairci'],
  ],
  '7': [
    ['Am                     Em', 'Si dans ta rétine l’amour'],
    ['F                         C', 'Ne supporte plus la lumière du jour'],
    ['Am                     Em', 'Je rallumerai les étoiles autour'],
    ['F                            C', "J'apprendrai à compter jusqu'à toujours"],
    ['Am', 'Et toi tu pourras compter sur moi'],
  ],
  '8': [
    ['Em', 'Et ça finira jamais'],
    ['F', 'Ça finira jamais'],
    ['C', 'Ça finira jamais'],
    ['Am               Em', 'Et ça finira jamais'],
    ['F', 'Ça finira jamais'],
    ['C', 'Ça finira jamais'],
  ],
  '9': [
    ['Am                    Em', 'Si dans ta rétine l’amour'],
    ['F                         C', 'Ne supporte plus la lumière du jour'],
    ['Am                    Em', 'Je rallumerai les étoiles autour'],
    ['F                            C', "J'apprendrai à compter jusqu'à toujours"],
    ['Am', 'Et toi tu pourras compter sur moi'],
  ],
}
